name: calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  battery_plus: ^6.0.1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
